"use client"

import { useRouter } from "next/navigation"
import { DataTable, type Column } from "@/components/data-table"
import { StatusBadge } from "@/components/status-badge"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { formatCurrency, formatDate } from "@/lib/format"

interface LabelItem {
	id: string
	orderId: string
	carrierId: string
	trackingNumber: string
	labelUrl: string | null
	status: string
	weight: string | null
	cost: string | null
	createdAt: Date
	carrierName: string
	orderNumber: string
}

interface LabelsClientProps {
	labels: LabelItem[]
	totalCount: number
	currentPage: number
	currentStatus?: string
}

const statuses = ["pending", "printed", "shipped", "delivered"]

export function LabelsClient({ labels, totalCount, currentPage, currentStatus }: LabelsClientProps) {
	const router = useRouter()

	const columns: Column<LabelItem>[] = [
		{
			key: "order",
			header: "Order",
			cell: (row) => <span className="text-sm font-medium">#{row.orderNumber}</span>,
		},
		{
			key: "carrier",
			header: "Carrier",
			cell: (row) => <span className="text-sm">{row.carrierName}</span>,
		},
		{
			key: "tracking",
			header: "Tracking",
			cell: (row) => (
				<span className="text-xs font-mono text-muted-foreground">{row.trackingNumber}</span>
			),
		},
		{
			key: "status",
			header: "Status",
			cell: (row) => <StatusBadge status={row.status} type="label" />,
		},
		{
			key: "cost",
			header: "Cost",
			cell: (row) => (
				<span className="text-sm">{row.cost ? formatCurrency(row.cost) : "—"}</span>
			),
		},
		{
			key: "createdAt",
			header: "Created",
			cell: (row) => (
				<span className="text-xs text-muted-foreground">{formatDate(row.createdAt)}</span>
			),
		},
	]

	return (
		<>
		<div>
			<h2 className="text-lg font-semibold">Shipping Labels</h2>
			<p className="text-sm text-muted-foreground">Labels generated by carriers for order shipments.</p>
		</div>
		<DataTable
			columns={columns}
			data={labels}
			searchPlaceholder="Search labels..."
			totalCount={totalCount}
			currentPage={currentPage}
			pageSize={30}
			getId={(row) => row.id}
			onRowClick={(row) => router.push(`/shipping/labels/${row.id}`)}
			emptyMessage="No shipping labels"
			emptyDescription="Labels will appear here when created for orders."
			filters={
				<Select
					value={currentStatus ?? "all"}
					onValueChange={(value) => {
						const params = new URLSearchParams(window.location.search)
						if (value && value !== "all") {
							params.set("status", value)
						} else {
							params.delete("status")
						}
						params.delete("page")
						router.push(`/shipping/labels?${params.toString()}`)
					}}
				>
					<SelectTrigger className="h-9 w-full sm:w-[160px]">
						<SelectValue placeholder="All Statuses" />
					</SelectTrigger>
					<SelectContent>
						<SelectItem value="all">All Statuses</SelectItem>
						{statuses.map((s) => (
							<SelectItem key={s} value={s}>
								{s.replace(/\b\w/g, (c) => c.toUpperCase())}
							</SelectItem>
						))}
					</SelectContent>
				</Select>
			}
		/>
		</>
	)
}
